openapi: 3.1.0

info:
  title: RAP API
  version: "v1"

paths:
  /backend/status/:
    get:
      security:
        - bearerAuth: []
      description: |
        Get the status (flags) for all backends.
      tags:
        - backends
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - backends
                properties:
                  backends:
                    type: array
                    items:
                      type: object
                      required:
                        - name
                        - last_seen
                        - paused
                        - db_maintenance
                      properties:
                        name:
                         type: string
                         description: Name of backend
                        last_seen:
                          type: object
                          required:
                            - since
                          properties:
                            since:
                              $ref: "#/components/schemas/backendFlagSince"
                        paused:
                          description: Backend paused status (determines whether backend accepts new jobs)
                          type: object
                          required:
                            - status
                            - since
                          properties:
                            status:
                              $ref: "#/components/schemas/backendFlagStatus"
                            since:
                              $ref: "#/components/schemas/backendFlagSince"
                        db_maintenance:
                          type: object
                          required:
                            - status
                            - since
                            - type
                          properties:
                            status:
                              $ref: "#/components/schemas/backendFlagStatus"
                            since:
                              $ref: "#/components/schemas/backendFlagSince"
                            type:
                              type: string
                              enum:
                                - scheduled
                                - manual
                              nullable: true
              examples:
                normal_operation:
                  description: Backend 'test' operating normally
                  value:
                    backends:
                      - name: test
                        last_seen:
                          since: 2025-08-12T11:30:45.123456Z
                        paused:
                          status: off
                          since: 2025-08-12T11:30:45.123456Z
                        db_maintenance:
                          status: off
                          since: null
                          type: null
                paused:
                  description: Backend 'test' paused
                  value:
                    backends:
                      - name: test
                        last_seen:
                          since: 2025-08-12T11:30:45.123456Z
                        paused:
                          status: on
                          since: 2025-08-12T11:30:45.123456Z
                        db_maintenance:
                          status: off
                          since: null
                          type: null
                manual_db_maintenance:
                  description: Backend 'test' in manual db maintenance
                  value:
                    backends:
                      - name: test
                        last_seen:
                          since: 2025-08-12T11:30:45.123456Z
                        paused:
                          status: off
                          since: 2025-08-12T11:30:45.123456Z
                        db_maintenance:
                          status: off
                          since: 2025-08-12T11:30:45.123456Z
                          type: manual
        401:
          $ref: "#/components/responses/401Unauthorized"

  /rap/cancel/:
      post:
        security:
          - bearerAuth: []
        description: |
          Cancel one or more actions.
        tags:
        - rap_operations
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cancelRequestBody"
              examples:
                example1:
                  value:
                    job_request_id: a1b2c3d4e5f6g7h8
                    actions: ["action1"]
                example2:
                  value:
                    job_request_id: abcdefgh12345678
                    actions: ["action2", "action3"]
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: string
                    details:
                      type: string
                    count:
                      description: Number of actions cancelled
                      type: integer
                examples:
                  success:
                    description: 2 actions successfully cancelled
                    value:
                      success: ok
                      details: 2 actions cancelled
                      count: 2
          400:
            description: Bad response
            content:
              application/json:
                schema:
                  type: object
                  required:
                   - error
                   - details
                  properties:
                    error:
                      type: string
                    details:
                      type: string
                    job_request_id:
                      description: job_request_id parameter
                      type: string
                    not_found:
                      description: actions requested for cancellation that do not exist for the requested job_request_id
                      type: array
                      items:
                        type: string
                examples:
                  validation_error:
                    description: Missing job_request_id
                    value:
                      error: Validation error
                      details: "Invalid request body received: 'job_request_id' is a required property"
                  data_error1:
                    description: No jobs found matching job_request_id
                    value:
                      error: job request not found
                      details: No jobs found for job_request_id abcdefgh12345678
                      job_request_id: abcdefgh12345678
                  data_error2:
                    description: Jobs matching requested cancel actions are not found
                    value:
                      error: Jobs not found
                      details: "Jobs matching requested cancelled actions could not be found: action1,action2"
                      job_request_id: abcdefgh12345678
                      not_found: ["action1", "action2"]
          401:
            $ref: "#/components/responses/401Unauthorized"
          403:
            $ref: "#/components/responses/403NotAllowedBackend"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: token

  schemas:
    backendFlagStatus:
      # Can be referenced as '#/components/schemas/backendFlagStatus'
      type: string
      enum:
        - "on"
        - "off"
    backendFlagSince:
      # Can be referenced as '#/components/schemas/backendFlagSince'
      type: string
      nullable: true
      pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{6}Z$'
      description: Time this property was last set
    cancelRequestBody:
      # Can be referenced as '#/components/schemas/cancelRequestBody'
      type: object
      required:
        - job_request_id
        - actions
      properties:
        job_request_id:
          type: string
          pattern: "^[a-z0-9]{16}$"
        actions:
          type: array
          minItems: 1
          items:
            type: string

  responses:
    401Unauthorized:
      # Can be referenced as '#/components/responses/401Unauthorized'
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: string
          examples:
            invalid_token:
              value:
                error: "Unauthorized"
                details: "Invalid token"
    403NotAllowedBackend:
      # Can be referenced as '#/components/responses/404UnknownBackend'
      description: unknown backend
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: string
          examples:
            not_allowed_for_backend:
              value:
                error: "Not allowed"
                details: "Not allowed for backend 'foo'"

security:
  - bearerAuth: []

tags:
  - name: backends
    x-displayName: Backend status
    description: Endpoints that provide information about backend status.
  - name: rap_operations
    x-displayName: RAP Operations
    description: Endpoints that perform operations on RAPs
